### ISSUE TITLE
HTTPS LB Create Fails

### ISSUE THREAD

**Issue by s-archer** [volterraedge/terraform-provider-volterra#104]
It seems that the recent platform upgrade changed the API spec, but the latest provider version v0.11.0 (released yesterday) doesn't match.  The terraform error I'm getting is:

```Field spec.loadbalancer_type.https_auto_cert.path_normalize_choice should be not nil, got nil in request. ```

The updated TF docs suggest that I need to add '[dis|en]able_path_normalize = true' to the https or https_auto_cert block.  But if i do, I get the following error:

```An argument named "disable_path_normalize" is not expected here.```

Help appreciated.

**Comment by madhukar32** [comment]
@s-archer: We have released a new version v0.11.2. Could you pls try that, there are two arguements which needs to be set
`multi_lb_app` or `single_lb_app` must be set and in more_options you need to set `disable_path_normalize` or `enable_path_normalize`. Documentation should be updated on what these field mean

**Comment by s-archer** [comment]
Yes, v0.11.2 and the additional arguments fixes the problem.  Thank you for fixing this so quickly :)
