### ISSUE TITLE
provider fails to identify existing volterra_discovery resource during plan

### ISSUE THREAD

**Issue by mjmenger** [volterraedge/terraform-provider-volterra#193]
During the plan stage of `terraform apply` or `terraform plan`, the provider fails to identify an existing volterra_discovery resource. 

```shell
Terraform will perform the following actions:

  # volterra_discovery.cluster-discovery will be created
  + resource "volterra_discovery" "discovery" {
      + description   = "Service discovery"
      + id            = (known after apply)
      + name          = "aname"
      + namespace     = "system"
      + no_cluster_id = true

      + discovery_k8s {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }

      + where {
          + site {
              + network_type = "VIRTUAL_NETWORK_SITE_LOCAL_INSIDE"

              + ref {
                  + kind      = (known after apply)
                  + name      = "aname"
                  + namespace = "system"
                }
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Then during the `apply` the process fails with an 'Object already exists' error.

```shell
volterra_discovery.discovery: Creating...
╷
│ Error: error creating Discovery: Creating object: Unsuccessful POST at URL https://tenant.console.ves.volterra.io/api/public/namespaces/system/discoverys, status code 409, body {"code":6,"details":[],"message":"Object already exists"}, err %!s(<nil>)
│ 
│   with volterra_discovery.discovery,
│   on abc.tf line 1, in resource "volterra_discovery" "discovery":
```

The expected result is for Terraform to see the existing resource and require no changes.

**Comment by mjmenger** [comment]
after further testing, it looks like the 409 error is being generated after successfully creating the Service Discovery object. The Terraform project used to create the `volterra_discovery` resource was run several times over the past two weeks without this error. This error only started occurring over the past week.

**Comment by madhukar32** [comment]
@devopsinout : Can you pls take a look at this?

**Comment by mjmenger** [comment]
After even more testing, I found that I had duplicate code that was creating the same `volterra_discover` resource. So the 409 error was actually the correct response. Consequently, the cause is on my end, and this issue can be closed.
