### ISSUE TITLE
Origin pool doesn't respond

### ISSUE THREAD

**Issue by AndreJosephL** [volterraedge/terraform-provider-volterra#217]
Each time I run a script that contains an origin pool, that plugin doesn't work
![origin pool error](https://github.com/volterraedge/terraform-provider-volterra/assets/130710707/dc05d412-6b31-4c0e-b3c2-44adcb793785)

**Comment by AndreJosephL** [comment]
.

**Comment by SanjeetKr7** [comment]
@AndreJosephL This issue has been fixed. Please reopen it if the issue persists.
