### ISSUE TITLE
resource volterra_alert_policy - Field spec.routes.matcher.custom.alertlabel.matcher_type should be not nil

### ISSUE THREAD

**Issue by eissko** [volterraedge/terraform-provider-volterra#220]
The terraform resource "volterra_alert_policy" failing when configuring "alert policy -> routes -> custom" as part of the code depicted below:

resource volterra_alert_policy:
```hcl
   custom {
        alertlabel  {
            name  = "env"
            value {
                exact_match = "${var.environment}"
            }
        }
        severity  {
            exact_match = "CRITICAL"
        }
    }
```

terraform plan is ok:

      + routes {
          + send = true

          + custom {
              + alertlabel {
                  + name = "env"

                  + value {
                      + exact_match = "edu"
                    }
                }
              + severity {
                  + exact_match = "CRITICAL"
                }
            }

          + notification_parameters {
              + default         = true
              + group_interval  = "10h"
              + group_wait      = "5m"
              + repeat_interval = "4h"
            }
        }
    }

but terraform apply fails. 

It looks like bug in go code in validation which does not match the required schema.

**Comment by abhinavgrover15** [comment]
Ack. I will get back to you on this.

**Comment by eissko** [comment]
Hi @abhinavgrover15, have you found anything in this matter? Do you need any help or inputs?

**Comment by eissko** [comment]
@abhinavgrover15 I will close this issue because I think I misunderstood alertlabel attribute. I used it inproperly. thanks
