### ISSUE TITLE
Changes to resources made outside of Terraform are not detected

### ISSUE THREAD

**Issue by michaelbuemi** [volterraedge/terraform-provider-volterra#225]
I've tested both volterra_ip_prefix_set and volterra_origin_pool. Making a change to the description will be detected, but not if I change an IP in the prefix set or the origin servers.

For example, I've changed this origin IP from 192.0.2.24 to 192.0.2.25.

![foo-dev-origins](https://github.com/volterraedge/terraform-provider-volterra/assets/22860149/d991f4d5-9f45-470c-806e-be52f32341b2)

Here is the state in our TF Enterprise:

![foo-dev-origins-state](https://github.com/volterraedge/terraform-provider-volterra/assets/22860149/192351e6-2e95-4e8c-864f-f0d86f3c5452)

And here is the terraform plan run, where the only detected modification is the description on the prefix set. (Which was in fact a change, just not the ONLY change ... )

```module.foo-prod.volterra_namespace.ns: Refreshing state... [id=827dd169-af86-4e9c-a819-4cb7a4b71c4d]
module.foo-dev.volterra_certificate_chain.entrust-chain: Refreshing state... [id=2f5eb8b3-b74d-46e1-81d8-4d764a7a16da]
module.foo-dev.volterra_namespace.ns: Refreshing state... [id=0cd411cd-098e-4067-99ba-2fe3d3eabefb]
module.foo-dev.volterra_origin_pool.foo-dev-origin: Refreshing state... [id=49ba25d3-d71e-4bda-bd9e-a647d9115d8a]
module.foo-dev.volterra_ip_prefix_set.allow-list: Refreshing state... [id=b3494b09-8722-4829-b660-bab194d12379]
2023-10-16T14:31:22.813Z [WARN]  Provider "registry.terraform.io/volterraedge/volterra" produced an unexpected new value for module.foo-dev.volterra_ip_prefix_set.allow-list during refresh.
      - .description: was cty.StringVal("Example allow list."), but now cty.StringVal("Example deny list.")
module.foo-prod.volterra_ip_prefix_set.allow-list: Refreshing state... [id=8e5e6c4a-094d-4a4e-8359-ac0937f7c304]
module.foo-dev.volterra_ip_prefix_set.allow-list: Drift detected (update)

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.foo-dev.volterra_ip_prefix_set.allow-list will be updated in-place
  ~ resource "volterra_ip_prefix_set" "allow-list" {
      ~ description = "Example deny list." -> "Example allow list."
        id          = "b3494b09-8722-4829-b660-bab194d12379"
        name        = "allow-list"
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by megamattzilla** [comment]
I can replicate this with resource `volterra_tcp_loadbalancer`. I can change the load balancers port in the portal to something totally different but when I rerun terraform it does not detect any changes.

**Comment by abhinavgrover15** [comment]
@megamattzilla Drift will be supported for below selected resources in upcoming release.

1. TCP Load Balancer
2. HTTP Load Balancer
3. Origin Pools
4. Service Policy
5. IP Prefix Set.

Thank you for your patience and co-operation.

**Comment by megamattzilla** [comment]
Thats great news, thanks for the update!!

**Comment by eissko** [comment]
@abhinavgrover15 thanks for heads-up. I was just about to create an issue that active service policy drift is not detected. I understand based on your comment this will be implemented. do you know which release version is this fix targeted to? thanks. Peter
