### ISSUE TITLE
Authentication: allow to pass p12 bundle file by content  

### ISSUE THREAD

**Issue by awasilyev** [volterraedge/terraform-provider-volterra#227]
I'm trying to deploy terraform code with volterra resources via terraform cloud (app.terraform.com) and facing a blocker:
There is no way to predefine a p12 bundle file on the terraform worker there. Storing that file in a git with terraform code is absolutely insecure. Terraform cloud have support for defining a sensitive environment variables, and it is possible to use that way for authentication of other providers (like aws, gcp). It will be great to have ability to pass p12 bundle file content via environment variable.

**Comment by awasilyev** [comment]
I made a small dirty pr that will add that functionality: https://github.com/volterraedge/terraform-provider-volterra/pull/226. Unfortunately I can't test it because I don't have access to the gopkg.volterra.us and can't build provider locally.

**Comment by mb38291** [comment]
I need this as well. The P12 requirement does not play nicely with Terraform in general.

**Comment by abhinavgrover15** [comment]
This has been made available with 0.11.29.
