### ISSUE TITLE
Example health check usage is mixed up between DNS and HTTP HealthChecks

### ISSUE THREAD

**Issue by GlenWillms** [volterraedge/terraform-provider-volterra#247]
For the two links below, the body of the examples, and the help details appear to be swapped 

https://registry.terraform.io/providers/volterraedge/volterra/latest/docs/resources/volterra_dns_lb_health_check

https://registry.terraform.io/providers/volterraedge/volterra/latest/docs/resources/volterra_healthcheck

...and older version of thee healthcheck documentation doesn't have this issue: https://registry.terraform.io/providers/volterraedge/volterra/0.11.13/docs/resources/volterra_healthcheck

**Comment by pranavskumar** [comment]
@GlenWillms The example and help details in the documentation seem to be correct.

**Comment by GlenWillms** [comment]
I concur. It looks good now.
