### ISSUE TITLE
0.11.33 plugin // the plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call

### ISSUE THREAD

**Issue by dgst77** [volterraedge/terraform-provider-volterra#251]
│ Error: Plugin did not respond
│ 
│   with volterra_http_loadbalancer.https-lb,
│   on f5xc_lb-https_blindfold.tf line 78, in resource "volterra_http_loadbalancer" "https-lb":
│   78: resource "volterra_http_loadbalancer" "https-lb" {

Stack trace from the terraform-provider-volterra_v0.11.33 plugin:

panic: interface conversion: interface {} is bool, not *schema.Set

goroutine 227 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setSet(0x14003cb7830, {0x1400345f2c0, 0x5, 0x5}, {0x1118c4e80, 0x118654468}, 0x140000d48c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:343 +0x678
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0x14003cb7830, {0x1400345f2c0, 0x5, 0x5}, {0x1118c4e80, 0x118654468})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:107 +0x120
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0x140038f6480?, {0x140038f6480?, 0x4, 0x4}, {0x111ad43c0, 0x1400230cf90})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:222 +0x23c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0x14003cb7830, {0x140038f6480, 0x4, 0x4}, {0x111ad43c0, 0x1400230cf90})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:109 +0xf8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:122
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0x14003cb7830, {0x1400230dce0?, 0x3, 0x3}, {0x111899dc0, 0x14003cb76e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:142 +0x434
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0x14003cb7830, {0x1400230dce0, 0x3, 0x3}, {0x111899dc0, 0x14003cb76e0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:103 +0x90
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0x140039edb40?, {0x140039edb40?, 0x2, 0x2}, {0x111ad43c0, 0x1400230cae0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:222 +0x23c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0x14003cb7830, {0x140039edb40, 0x2, 0x2}, {0x111ad43c0, 0x1400230cae0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:109 +0xf8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:122
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0x14003cb7830, {0x1400230d7f0?, 0x1, 0x1}, {0x111899dc0, 0x14003cb7740})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:142 +0x434
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0x14003cb7830, {0x1400230d7f0, 0x1, 0x1}, {0x111899dc0, 0x14003cb7740})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:103 +0x90
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).WriteField(0x14003cb7830, {0x1400230d7f0, 0x1, 0x1}, {0x111899dc0, 0x14003cb7740})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:89 +0x38c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setSet(0x14003cb7770, {0x1400230d7d0, 0x3, 0x3}, {0x111899dc0, 0x14003cb7740}, 0x140000f72c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:306 +0x2c8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0x14003cb7770, {0x1400230d7d0, 0x3, 0x3}, {0x111899dc0, 0x14003cb7740})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:107 +0x120
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setObject(0x140039edb20?, {0x140039edb20?, 0x2, 0x2}, {0x111ad43c0, 0x1400230cab0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:222 +0x23c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0x14003cb7770, {0x140039edb20, 0x2, 0x2}, {0x111ad43c0, 0x1400230cab0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:109 +0xf8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList.func1(...)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:122
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setList(0x14003cb7770, {0x140037697c0?, 0x1, 0x1}, {0x111899dc0, 0x14003cb7758})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:142 +0x434
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0x14003cb7770, {0x140037697c0, 0x1, 0x1}, {0x111899dc0, 0x14003cb7758})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:103 +0x90
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).WriteField(0x14003cb7770, {0x140037697c0, 0x1, 0x1}, {0x111899dc0, 0x14003cb7758})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:89 +0x38c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).setSet(0x1400460e420, {0x140037697c0, 0x1, 0x1}, {0x111899dc0, 0x14003cb7758}, 0x140000f7400)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:306 +0x2c8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).set(0x1400460e420, {0x140037697c0, 0x1, 0x1}, {0x111899dc0, 0x14003cb7758})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:107 +0x120
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MapFieldWriter).WriteField(0x1400460e420, {0x140037697c0, 0x1, 0x1}, {0x111899dc0, 0x14003cb7758})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/field_writer_map.go:89 +0x38c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0x14004581a80, {0x10d34b11c, 0x5}, {0x111899dc0, 0x14003cb7758})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource_data.go:227 +0x20c
github.com/volterraedge/terraform-provider-volterra/volterra/drift_detection.DriftDetectionSpec(0x14004581a80?, {0x1442af880?, 0x14003cb6510?})
	github.com/volterraedge/terraform-provider-volterra/volterra/drift_detection/drift_detection_resource_auto_http_loadbalancer.go:3968 +0x1828
github.com/volterraedge/terraform-provider-volterra/volterra.setHttpLoadbalancerFields(0x14002276358?, 0x112797668?, {0x1442af880, 0x14003cb6510})
	github.com/volterraedge/terraform-provider-volterra/volterra/resource_auto_volterra_http_loadbalancer.go:38934 +0x1e8
github.com/volterraedge/terraform-provider-volterra/volterra.resourceVolterraHttpLoadbalancerRead(0x14004581a80, {0x112225f00?, 0x14002276358})
	github.com/volterraedge/terraform-provider-volterra/volterra/resource_auto_volterra_http_loadbalancer.go:38913 +0x2f8
github.com/volterraedge/terraform-provider-volterra/volterra.resourceVolterraHttpLoadbalancerCreate(0x14004581a80?, {0x112225f00?, 0x14002276358})
	github.com/volterraedge/terraform-provider-volterra/volterra/resource_auto_volterra_http_loadbalancer.go:38896 +0x4310
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1127976d8?, {0x1127976d8?, 0x14003451f80?}, 0xd?, {0x112225f00?, 0x14002276358?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:695 +0x134
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x14000fe8a80, {0x1127976d8, 0x14003451f80}, 0x14003bdcb60, 0x14003ee1000, {0x112225f00, 0x14002276358})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:837 +0x86c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140023fc5a0, {0x1127976d8?, 0x14003451e60?}, 0x1400117f590)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:1021 +0xb70
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140001a0be0, {0x1127976d8?, 0x14003451530?}, 0x14003bd1730)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x3b8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1122899c0?, 0x140001a0be0}, {0x1127976d8, 0x14003451530}, 0x14003bd16c0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400276c000, {0x11280d5a0, 0x14001978000}, 0x14002e24000, 0x140018196e0, 0x118737ac0, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1374 +0xbb4
google.golang.org/grpc.(*Server).handleStream(0x1400276c000, {0x11280d5a0, 0x14001978000}, 0x14002e24000, 0x0)
	google.golang.org/grpc@v1.58.3/server.go:1751 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.3/server.go:986 +0xb4
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.58.3/server.go:997 +0x174

Error: The terraform-provider-volterra_v0.11.33 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by dgst77** [comment]
please note older plugin 0.11.32 and 31 works just fine

**Comment by SanjeetKr7** [comment]
@dgst77 Could you please share the tf code with masked credential?

**Comment by dgst77** [comment]
> @dgst77 Could you please share the tf code with masked credential?

Terraform v1.8.4
on darwin_arm64

terraform {
  required_version = ">= 0.12.9, != 0.13.0"

  required_providers {
    volterra = {
      source  = "volterraedge/volterra"
      version = ">=0.0.6"

    }
  }
}

provider "volterra" {
  api_p12_file = "../..../.../xxxx.p12"
  url          = var.api_url
}

module "shell_blindfold" {
  source  = "Invicton-Labs/shell-data/external"
  command_unix = "./scripts/blindfold.sh ${var.lb_cert} ${var.lb_key}"
  fail_on_stderr = true
  environment = {
    VES_P12_PASSWORD = "${var.VES_PASSWORD}"
    
  }
}

locals {
  description  = "Used to store the output of the blindfold.sh script"
  blindfoldb64 = sensitive(split(" ", module.shell_blindfold.stdout))
}

locals {
  app_vars = yamldecode(file("./../../../xxxxx.yaml"))
}

output "app_vars" {
  value = local.app_vars
}


# Health Check

resource "volterra_healthcheck" "http-health-check-nginx" {
  name      = format("http-hc-nginx-%s", local.app_vars.base)
  namespace = local.app_vars.namespace
  http_health_check {
    path                  = "/httpd/HealthCheck"
    host_header           = local.app_vars.origin_server_expected_nginx_fqdn
    expected_status_codes = ["200"]
  }
  healthy_threshold   = 2
  interval            = 30
  timeout             = 1
  unhealthy_threshold = 2
}

resource "volterra_healthcheck" "http-health-check-apache" {
  name      = format("http-hc-apache-%s", local.app_vars.base)
  namespace = local.app_vars.namespace
  http_health_check {
    path                  = "/apachehealth"
    host_header           = local.app_vars.origin_server_expected_apache_fqdn
    expected_status_codes = ["200"]
  }
  healthy_threshold   = 2
  interval            = 30
  timeout             = 1
  unhealthy_threshold = 2
}

resource "volterra_origin_pool" "origin-pool-nginx" {
  name      = format("origin-pool-nginx-%s", local.app_vars.base)
  namespace = local.app_vars.namespace
  origin_servers {
    public_name {
      dns_name = local.app_vars.origin_server_nginx
    }
    labels = {
    }
  }
  port = "443"
  use_tls {
    tls_config {
    }
    skip_server_verification = true
  }
  endpoint_selection     = "LOCALPREFERED"
  loadbalancer_algorithm = "LB_OVERRIDE"
  healthcheck {
    name = volterra_healthcheck.http-health-check-nginx.name
  }
}

resource "volterra_origin_pool" "origin-pool-apache" {
  name      = format("origin-pool-apache-%s", local.app_vars.base)
  namespace = local.app_vars.namespace
  origin_servers {
    public_name {
      dns_name = local.app_vars.origin_server_apache
    }
    labels = {
    }
  }
  port = "443"
  use_tls {
    tls_config {
    }
    skip_server_verification = true
  }
  endpoint_selection     = "LOCALPREFERED"
  loadbalancer_algorithm = "LB_OVERRIDE"
  healthcheck {
    name = volterra_healthcheck.http-health-check-apache.name
  }
}

# Load-Balancer
resource "volterra_http_loadbalancer" "https-lb" {
  depends_on = [volterra_origin_pool.origin-pool-nginx, volterra_origin_pool.origin-pool-apache]
  name       = format("%s-lb-%s", local.app_vars.base, local.app_vars.namespace)
  namespace  = local.app_vars.namespace
  domains    = [local.app_vars.origin_app_domain]
  https {
    port                  = "443"
    add_hsts              = true
    http_redirect         = true
    enable_path_normalize = true
    tls_parameters {
      no_mtls = true
      tls_config {
        default_security = true
      }
      tls_certificates {
        # Use the Base64 certificate generated by the blindfold.sh script
        certificate_url = (local.blindfoldb64[0])
        public_key {
          blindfold_secret_info {
            decryption_provider = ""
            store_provider      = ""
            # Use the Blindfold secret generated by the blindfold.sh script
            location = (local.blindfoldb64[1])
          }
          secret_encoding_type = "EncodingNone"
        }
      }
    }
  }

  default_route_pools {
    pool {
      namespace = local.app_vars.namespace
      name      = format("origin-pool-nginx-%s", local.app_vars.base)
    }
    priority = 1
    weight   = 1
    
  }

  advertise_on_public_default_vip = false
  advertise_on_public {
    public_ip {
      namespace = "shared"
      name      = "ip-72-19-3-97"
    }
  }
  user_identification {
    name      = "user-identification"
    namespace = "shared"
    tenant    = "shared"
  }
  app_firewall {
    name      = "zerobxc-global-default-appfw"
    namespace = "shared"
  }
  active_service_policies {
    policies {
      name      = "zerobxc-default-service-policy"
      namespace = "shared"
    }
    policies {
      name      = "geo-filter-shared"
      namespace = "shared"
    }
    policies {
      name      = "ip-rep-shared"
      namespace = "shared"
    }
    policies {
      name      = "ip-block-list-sp"
      namespace = "shared"
    }
    policies {
      name      = "method-block-shared"
      namespace = "shared"
    }
    policies {
      name      = "ves-io-allow-all"
      namespace = "shared"
      tenant    = "ves-io"
    }
  }
  user_id_client_ip    = true
  source_ip_stickiness = true
  routes {
    simple_route {
      path {
        regex = "^\\/public\\/api\\/.*|^\\/secure\\/api\\/.*|^\\/public\\/myt-api\\/.*"
      }
      origin_pools {
        pool {
          name = format("origin-pool-apache-%s", local.app_vars.base)
          namespace = local.app_vars.namespace
        }
      }
      host_rewrite = local.app_vars.origin_server_expected_apache_fqdn
      advanced_options {
        request_headers_to_add { 
          name = "X-apex-HOST"
          value = local.app_vars.origin_server_expected_public_fqdn
          append = "false"
        }
        request_headers_to_add { 
          name = "x-apex-partition"
          value = "west1"
          append = "false"
        }
        request_headers_to_add { 
          name = "X-Forwarded-Host"
          value = local.app_vars.origin_server_expected_public_fqdn
          append = "false"
        }
        request_headers_to_add { 
          name = "X-Forwarded-Port"
          value = "443"
          append = "false"
        }
        request_headers_to_add { 
          name = "X-Forwarded-Proto"
          value = "https"
          append = "false"
        }
      }
    }
  }
  routes {
    simple_route {
      path {
        regex = "^\\/public\\/.*"
      }
      origin_pools {
        pool {
          name = format("origin-pool-nginx-%s", local.app_vars.base)
          namespace = local.app_vars.namespace
        }
      }
      host_rewrite = local.app_vars.origin_server_expected_public_fqdn
      advanced_options {
        request_headers_to_add { 
          name = "X-apex-HOST"
          value = local.app_vars.origin_server_expected_public_fqdn
          append = "false"
        }
        request_headers_to_add { 
          name = "x-apex-partition"
          value = "west1"
          append = "false"
        }
        request_headers_to_add { 
          name = "X-Forwarded-Host"
          value = local.app_vars.origin_server_expected_public_fqdn
          append = "false"
        }
        request_headers_to_add { 
          name = "X-Forwarded-Port"
          value = "443"
          append = "false"
        }
        request_headers_to_add { 
          name = "X-Forwarded-Proto"
          value = "https"
          append = "false"
        }
      }
    }
  }

}

**Comment by dgst77** [comment]
if i change the provider blow ro the below all works ...there is an issue with the latest plugin 0.11.33

required_providers {
volterra = {
source = "volterraedge/volterra"
version = **"<=0.11.32"**

**Comment by SanjeetKr7** [comment]
@dgst77 Could you please tell me which field is present in this line?
`78: resource "volterra_http_loadbalancer" "https-lb" {`

**Comment by dgst77** [comment]
below is the entire block of the lb resources 

resource "volterra_http_loadbalancer" "https-lb" {
depends_on = [volterra_origin_pool.origin-pool-nginx, volterra_origin_pool.origin-pool-apache]
name = format("%s-lb-%s", local.app_vars.base, local.app_vars.namespace)
namespace = local.app_vars.namespace
domains = [local.app_vars.origin_app_domain]
https {
port = "443"
add_hsts = true
http_redirect = true
enable_path_normalize = true
tls_parameters {
no_mtls = true
tls_config {
default_security = true
}
tls_certificates {
# Use the Base64 certificate generated by the blindfold.sh script
certificate_url = (local.blindfoldb64[0])
public_key {
blindfold_secret_info {
decryption_provider = ""
store_provider = ""
# Use the Blindfold secret generated by the blindfold.sh script
location = (local.blindfoldb64[1])
}
secret_encoding_type = "EncodingNone"
}
}
}
}

default_route_pools {
pool {
namespace = local.app_vars.namespace
name = format("origin-pool-nginx-%s", local.app_vars.base)
}
priority = 1
weight = 1

}

advertise_on_public_default_vip = false
advertise_on_public {
public_ip {
namespace = "shared"
name = "ip-x.x.x.x"
}
}
user_identification {
name = "user-identification"
namespace = "shared"
tenant = "shared"
}
app_firewall {
name = "zerobxc-global-default-appfw"
namespace = "shared"
}
active_service_policies {
policies {
name = "zerobxc-default-service-policy"
namespace = "shared"
}
policies {
name = "geo-filter-shared"
namespace = "shared"
}
policies {
name = "ip-rep-shared"
namespace = "shared"
}
policies {
name = "ip-block-list-sp"
namespace = "shared"
}
policies {
name = "method-block-shared"
namespace = "shared"
}
policies {
name = "ves-io-allow-all"
namespace = "shared"
tenant = "ves-io"
}
}
user_id_client_ip = true
source_ip_stickiness = true
routes {
simple_route {
path {
regex = "^\/public\/api\/.|^\/secure\/api\/.|^\/public\/myt-api\/."
}
origin_pools {
pool {
name = format("origin-pool-apache-%s", local.app_vars.base)
namespace = local.app_vars.namespace
}
}
host_rewrite = local.app_vars.origin_server_expected_apache_fqdn
advanced_options {
request_headers_to_add {
name = "X-apex-HOST"
value = local.app_vars.origin_server_expected_public_fqdn
append = "false"
}
request_headers_to_add {
name = "x-apex-partition"
value = "west1"
append = "false"
}
request_headers_to_add {
name = "X-Forwarded-Host"
value = local.app_vars.origin_server_expected_public_fqdn
append = "false"
}
request_headers_to_add {
name = "X-Forwarded-Port"
value = "443"
append = "false"
}
request_headers_to_add {
name = "X-Forwarded-Proto"
value = "https"
append = "false"
}
}
}
}
routes {
simple_route {
path {
regex = "^\/public\/."
}
origin_pools {
pool {
name = format("origin-pool-nginx-%s", local.app_vars.base)
namespace = local.app_vars.namespace
}
}
host_rewrite = local.app_vars.origin_server_expected_public_fqdn
advanced_options {
request_headers_to_add {
name = "X-apex-HOST"
value = local.app_vars.origin_server_expected_public_fqdn
append = "false"
}
request_headers_to_add {
name = "x-apex-partition"
value = "west1"
append = "false"
}
request_headers_to_add {
name = "X-Forwarded-Host"
value = local.app_vars.origin_server_expected_public_fqdn
append = "false"
}
request_headers_to_add {
name = "X-Forwarded-Port"
value = "443"
append = "false"
}
request_headers_to_add {
name = "X-Forwarded-Proto"
value = "https"
append = "false"
}
}
}
}

}

**Comment by dgst77** [comment]
Thanks for looking into this

**Comment by SanjeetKr7** [comment]
@dgst77 pls try to test with version v0.11.34.

**Comment by dgst77** [comment]
0.11.34 works flawlessly . Thanks 


Sent from Yahoo Mail for iPhone


On Thursday, July 4, 2024, 1:02 AM, SanjeetKr7 ***@***.***> wrote:




@dgst77 pls try to test with version v0.11.34.
