### ISSUE TITLE
unable to create additional site token

### ISSUE THREAD

**Issue by mattsawyer77** [volterraedge/terraform-provider-volterra#31]
I'm using the 0.2.1 provider, trying to use the `volterra_token` resource to create a new site token. The API returns 200 but nothing new is created and the first site token that already existed is returned.

```hcl
resource "volterra_token" "site_token" {
  name        = var.volterra_site_name
  namespace   = "system"
}
```

I've also noticed the API returns 200 if the namespace is something other than `system` -- is this intended behavior?

**Comment by madhukar32** [comment]
/dupe https://github.com/volterraedge/terraform-provider-volterra/issues/67
