### ISSUE TITLE
seemingly no way to confirm registration for a site

### ISSUE THREAD

**Issue by mattsawyer77** [volterraedge/terraform-provider-volterra#32]
Perhaps I'm missing something -- but it seems that only the passport section of the registration API's payload is exposed to terraform. There is no way to specify the token. How can one tell which registration it will confirm?

**Comment by madhukar32** [comment]
@mattsawyer77: After registration acceptance the id of the object will be the registration id it has accepted.

1. Token is used to determine for which tenant the volterra CE software will create a registration request
2. Once the registration request is created, user uses `volterra_registration_approval` resource to approve it in which the user gives cluster_name information which is nothing but the site name information and hostname of the specific node
3. If you have multiple nodes in a volterra site then there are multiple registration request which will be generated so user need to accept those registrations
