### ISSUE TITLE
Option for AWS VPC site to use existing route table

### ISSUE THREAD

**Issue by JeffGiroux** [volterraedge/terraform-provider-volterra#78]
I need a way to specific existing route table. Or preferrably, do NOT add a route table. 

In reference to...
resource "volterra_aws_vpc_site

I'm running a lab and setting up VPC prior with AWS module. It creates route tables for each subnet. I then create a Volterra AWS VPC site using that existing VPC and subnet. However, the Volterra site creation then tries to create a route table and associate to the existing subnets with route tables already. This causes Volterra to error.

Also opened ticket on AWS VPC module repo to see if I can get the AWS team to add a flag in their module to NOT create a RT for particular subnets. See https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/676

**Comment by madhukar32** [comment]
@JeffGiroux 

The reason behind creating new route tables and changing the subnet association is that user always does some or the other mistake in configuring the route tables. For example for SLI route table and  workload table we have seen users configuring wrong route table entries like having default route table pointing to internet gateway and when user does that we cannot really change that route to something else as terraform will complain
So there are only two options

We ask users to configure the route table for the subnet specified
We ask users not to configure the route table for the subnet specified and volterra will do it.

So we have gone with option # 2 for now as it will give us more control. This is same for assisted mode and manual mode

We are working on a new service which can dynamically decided few of the things as there are multiple limitations from terraform side. Until that service starts supporting this feature, I would suggest to not create route tables and then query the subnet associated with the route table after volterra site is deployed and then make changes to it

**Comment by madhukar32** [comment]
@JeffGiroux: Let me know if its ok to close this ticket

**Comment by madhukar32** [comment]
@JeffGiroux: Created this new aha idea for this request https://www.volterraideas.io/ideas/MESH-I-106
